import "server-only"

import { appConfig } from "@/lib/system/config/server"
import {
  appendPromptHistory,
  isTaskStarted,
  readPromptHistory,
  readTaskData,
} from "@/lib/onboarding/repository"
import {
  cleanupForbiddenWorkbenchFiles,
  filterWorkbenchPayloadByAllowlist,
  getLevelEditableWorkbenchFileMap,
  getLevelEditableWorkbenchFiles,
} from "@/lib/lab/workbench"
import {
  clearTaskCheckResult,
  failCurrentTaskLevelCheck,
  getAllLevelOverviews,
  getLevelById,
  getLevelForTaskItem,
  getLevelOverview,
  getLevelsCatalog,
  getTaskCheckResult,
  getTaskDoneTransition,
  getTaskLabContext,
  getTaskLevelHint,
  getTaskListItemById,
  getTasks,
  getTaskPendingTransition,
  markCurrentTaskLevelInitialized,
  markCurrentTaskLevelCheckTechnicalError,
  markTaskLevelInProgress,
  passCurrentTaskLevelCheck,
  resetTask,
  registerPromptForCurrentLevel,
  saveTaskCheckResult,
} from "@/lib/task/server"

export {
  appConfig,
  appendPromptHistory,
  clearTaskCheckResult,
  cleanupForbiddenWorkbenchFiles,
  failCurrentTaskLevelCheck,
  filterWorkbenchPayloadByAllowlist,
  getAllLevelOverviews,
  getLevelById,
  getLevelForTaskItem,
  getTaskCheckResult,
  getTaskDoneTransition,
  getLevelOverview,
  getLevelsCatalog,
  getLevelEditableWorkbenchFileMap,
  getLevelEditableWorkbenchFiles,
  getTaskLabContext,
  getTaskLevelHint,
  getTaskListItemById,
  getTasks as getTaskListItems,
  getTaskPendingTransition,
  isTaskStarted,
  markCurrentTaskLevelInitialized,
  markCurrentTaskLevelCheckTechnicalError,
  markTaskLevelInProgress,
  passCurrentTaskLevelCheck,
  readPromptHistory,
  readTaskData,
  resetTask,
  registerPromptForCurrentLevel,
  saveTaskCheckResult,
}
