import type { UiKitAdapter } from "../types"
import { mapDependencyNames } from "./shared"

const shadcnUiKitAdapter = {
  id: "shadcn",
  title: "shadcn/ui",
  installationOwner: "system",
  customizationPolicy: "reset-on-update",
  userInstallAllowed: false,
  prompt: {
    designSystemLabel: "shadcn/ui",
  },
  runtime: {
    dependencies: mapDependencyNames([
      "@base-ui/react",
      "@radix-ui/react-accordion",
      "@radix-ui/react-alert-dialog",
      "@radix-ui/react-aspect-ratio",
      "@radix-ui/react-avatar",
      "@radix-ui/react-checkbox",
      "@radix-ui/react-collapsible",
      "@radix-ui/react-context-menu",
      "@radix-ui/react-dialog",
      "@radix-ui/react-direction",
      "@radix-ui/react-dropdown-menu",
      "@radix-ui/react-hover-card",
      "@radix-ui/react-label",
      "@radix-ui/react-menubar",
      "@radix-ui/react-navigation-menu",
      "@radix-ui/react-popover",
      "@radix-ui/react-progress",
      "@radix-ui/react-radio-group",
      "@radix-ui/react-scroll-area",
      "@radix-ui/react-select",
      "@radix-ui/react-separator",
      "@radix-ui/react-slider",
      "@radix-ui/react-slot",
      "@radix-ui/react-switch",
      "@radix-ui/react-tabs",
      "@radix-ui/react-toggle",
      "@radix-ui/react-toggle-group",
      "@radix-ui/react-tooltip",
      "class-variance-authority",
      "clsx",
      "cmdk",
      "embla-carousel-react",
      "input-otp",
      "lucide-react",
      "next-themes",
      "react-day-picker",
      "react-resizable-panels",
      "recharts",
      "sonner",
      "tailwind-merge",
      "vaul",
    ]),
  },
} satisfies UiKitAdapter

export { shadcnUiKitAdapter }
